// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: chakraTestResults.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createChakraTestResults = `-- name: CreateChakraTestResults :one
INSERT INTO chakra_test_results (
    unique_id,
    email,
    chakra_name,
    chakra_score,
    chakra_status
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING unique_id, email, chakra_name, chakra_score, chakra_status, created_at, deleted_at
`

type CreateChakraTestResultsParams struct {
	UniqueID     uuid.UUID `json:"unique_id"`
	Email        string    `json:"email"`
	ChakraName   string    `json:"chakra_name"`
	ChakraScore  int32     `json:"chakra_score"`
	ChakraStatus string    `json:"chakra_status"`
}

func (q *Queries) CreateChakraTestResults(ctx context.Context, arg CreateChakraTestResultsParams) (ChakraTestResult, error) {
	row := q.db.QueryRowContext(ctx, createChakraTestResults,
		arg.UniqueID,
		arg.Email,
		arg.ChakraName,
		arg.ChakraScore,
		arg.ChakraStatus,
	)
	var i ChakraTestResult
	err := row.Scan(
		&i.UniqueID,
		&i.Email,
		&i.ChakraName,
		&i.ChakraScore,
		&i.ChakraStatus,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChakraTestResults = `-- name: GetChakraTestResults :many
SELECT unique_id, email, chakra_name, chakra_score, chakra_status, created_at
FROM chakra_test_results
WHERE email = $1 AND deleted_at = '0001-01-01 00:00:00Z'
ORDER BY created_at DESC
`

type GetChakraTestResultsRow struct {
	UniqueID     uuid.UUID `json:"unique_id"`
	Email        string    `json:"email"`
	ChakraName   string    `json:"chakra_name"`
	ChakraScore  int32     `json:"chakra_score"`
	ChakraStatus string    `json:"chakra_status"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) GetChakraTestResults(ctx context.Context, email string) ([]GetChakraTestResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, getChakraTestResults, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChakraTestResultsRow{}
	for rows.Next() {
		var i GetChakraTestResultsRow
		if err := rows.Scan(
			&i.UniqueID,
			&i.Email,
			&i.ChakraName,
			&i.ChakraScore,
			&i.ChakraStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
