// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: chakraTestOptionAnswers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createChakraTestOptionAnswersBatch = `-- name: CreateChakraTestOptionAnswersBatch :many
INSERT INTO chakra_test_option_answers (
    unique_id,
    email,
    unique_code,
    question,
    answer
)
SELECT unnest($1::uuid[]), unnest($2::text[]), unnest($3::text[]), unnest($4::text[]), unnest($5::text[])
RETURNING unique_id, email, unique_code, question, answer, created_at, deleted_at
`

type CreateChakraTestOptionAnswersBatchParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Column2 []string    `json:"column_2"`
	Column3 []string    `json:"column_3"`
	Column4 []string    `json:"column_4"`
	Column5 []string    `json:"column_5"`
}

func (q *Queries) CreateChakraTestOptionAnswersBatch(ctx context.Context, arg CreateChakraTestOptionAnswersBatchParams) ([]ChakraTestOptionAnswer, error) {
	rows, err := q.db.QueryContext(ctx, createChakraTestOptionAnswersBatch,
		pq.Array(arg.Column1),
		pq.Array(arg.Column2),
		pq.Array(arg.Column3),
		pq.Array(arg.Column4),
		pq.Array(arg.Column5),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChakraTestOptionAnswer{}
	for rows.Next() {
		var i ChakraTestOptionAnswer
		if err := rows.Scan(
			&i.UniqueID,
			&i.Email,
			&i.UniqueCode,
			&i.Question,
			&i.Answer,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
