// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: chakraBracelet.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const getChakraBracelet = `-- name: GetChakraBracelet :many
WITH custom_bracelets AS (
    SELECT chakra, name, image_url, product_link, type, created_at, deleted_at
    FROM chakra_bracelet 
    WHERE chakra = ANY($1::text[]) AND type = 0 -- Use sqlc.arg and type cast
    ORDER BY created_at DESC
),
random_bracelets AS (
    SELECT chakra, name, image_url, product_link, type, created_at, deleted_at
    FROM chakra_bracelet 
    WHERE type = 1
    ORDER BY RANDOM()
    LIMIT 2
)
SELECT chakra, name, image_url, product_link, type, created_at, deleted_at FROM random_bracelets	
UNION ALL
SELECT chakra, name, image_url, product_link, type, created_at, deleted_at FROM custom_bracelets
`

type GetChakraBraceletRow struct {
	Chakra      sql.NullString `json:"chakra"`
	Name        string         `json:"name"`
	ImageUrl    string         `json:"image_url"`
	ProductLink string         `json:"product_link"`
	Type        int32          `json:"type"`
	CreatedAt   time.Time      `json:"created_at"`
	DeletedAt   time.Time      `json:"deleted_at"`
}

func (q *Queries) GetChakraBracelet(ctx context.Context, chakras []string) ([]GetChakraBraceletRow, error) {
	rows, err := q.db.QueryContext(ctx, getChakraBracelet, pq.Array(chakras))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChakraBraceletRow{}
	for rows.Next() {
		var i GetChakraBraceletRow
		if err := rows.Scan(
			&i.Chakra,
			&i.Name,
			&i.ImageUrl,
			&i.ProductLink,
			&i.Type,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
