// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: emailRegistrations.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUserEmail = `-- name: CreateUserEmail :one
INSERT INTO email_registrations  (
  unique_id,
  email,
  chakra_info,
  language,
  unique_code,
  ip,
  country
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING unique_id, email, chakra_info, language, unique_code, ip, country, created_at, deleted_at
`

type CreateUserEmailParams struct {
	UniqueID   uuid.UUID      `json:"unique_id"`
	Email      string         `json:"email"`
	ChakraInfo sql.NullString `json:"chakra_info"`
	Language   string         `json:"language"`
	UniqueCode string         `json:"unique_code"`
	Ip         sql.NullString `json:"ip"`
	Country    sql.NullString `json:"country"`
}

type CreateUserEmailRow struct {
	UniqueID   uuid.UUID      `json:"unique_id"`
	Email      string         `json:"email"`
	ChakraInfo sql.NullString `json:"chakra_info"`
	Language   string         `json:"language"`
	UniqueCode string         `json:"unique_code"`
	Ip         sql.NullString `json:"ip"`
	Country    sql.NullString `json:"country"`
	CreatedAt  time.Time      `json:"created_at"`
	DeletedAt  time.Time      `json:"deleted_at"`
}

func (q *Queries) CreateUserEmail(ctx context.Context, arg CreateUserEmailParams) (CreateUserEmailRow, error) {
	row := q.db.QueryRowContext(ctx, createUserEmail,
		arg.UniqueID,
		arg.Email,
		arg.ChakraInfo,
		arg.Language,
		arg.UniqueCode,
		arg.Ip,
		arg.Country,
	)
	var i CreateUserEmailRow
	err := row.Scan(
		&i.UniqueID,
		&i.Email,
		&i.ChakraInfo,
		&i.Language,
		&i.UniqueCode,
		&i.Ip,
		&i.Country,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEmailRegistrationByTestNum = `-- name: GetEmailRegistrationByTestNum :one
SELECT unique_id, email, language, chakra_info, unique_code, created_at, deleted_at
FROM email_registrations
WHERE email = $1
ORDER BY created_at
OFFSET $2 LIMIT 1
`

type GetEmailRegistrationByTestNumParams struct {
	Email  string `json:"email"`
	Offset int32  `json:"offset"`
}

type GetEmailRegistrationByTestNumRow struct {
	UniqueID   uuid.UUID      `json:"unique_id"`
	Email      string         `json:"email"`
	Language   string         `json:"language"`
	ChakraInfo sql.NullString `json:"chakra_info"`
	UniqueCode string         `json:"unique_code"`
	CreatedAt  time.Time      `json:"created_at"`
	DeletedAt  time.Time      `json:"deleted_at"`
}

func (q *Queries) GetEmailRegistrationByTestNum(ctx context.Context, arg GetEmailRegistrationByTestNumParams) (GetEmailRegistrationByTestNumRow, error) {
	row := q.db.QueryRowContext(ctx, getEmailRegistrationByTestNum, arg.Email, arg.Offset)
	var i GetEmailRegistrationByTestNumRow
	err := row.Scan(
		&i.UniqueID,
		&i.Email,
		&i.Language,
		&i.ChakraInfo,
		&i.UniqueCode,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLatestEmailRegistration = `-- name: GetLatestEmailRegistration :one
SELECT unique_id, email, unique_code,created_at, deleted_at FROM email_registrations
WHERE email = $1
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestEmailRegistrationRow struct {
	UniqueID   uuid.UUID `json:"unique_id"`
	Email      string    `json:"email"`
	UniqueCode string    `json:"unique_code"`
	CreatedAt  time.Time `json:"created_at"`
	DeletedAt  time.Time `json:"deleted_at"`
}

func (q *Queries) GetLatestEmailRegistration(ctx context.Context, email string) (GetLatestEmailRegistrationRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestEmailRegistration, email)
	var i GetLatestEmailRegistrationRow
	err := row.Scan(
		&i.UniqueID,
		&i.Email,
		&i.UniqueCode,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReportByCode = `-- name: GetReportByCode :one
SELECT unique_id, email, chakra_info, language, unique_code, created_at, deleted_at
FROM email_registrations
WHERE unique_code = $1 AND deleted_at = '0001-01-01 00:00:00+00'
LIMIT 1
`

type GetReportByCodeRow struct {
	UniqueID   uuid.UUID      `json:"unique_id"`
	Email      string         `json:"email"`
	ChakraInfo sql.NullString `json:"chakra_info"`
	Language   string         `json:"language"`
	UniqueCode string         `json:"unique_code"`
	CreatedAt  time.Time      `json:"created_at"`
	DeletedAt  time.Time      `json:"deleted_at"`
}

func (q *Queries) GetReportByCode(ctx context.Context, uniqueCode string) (GetReportByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getReportByCode, uniqueCode)
	var i GetReportByCodeRow
	err := row.Scan(
		&i.UniqueID,
		&i.Email,
		&i.ChakraInfo,
		&i.Language,
		&i.UniqueCode,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
