// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type SessionLog struct {
	Uuid   uuid.UUID `json:"uuid"`
	UserID int64     `json:"user_id"`
	// references the name of the table of the session
	SessionType string `json:"session_type"`
	// either mr or mobile
	SessionPlatform string    `json:"session_platform"`
	CreatedAt       time.Time `json:"created_at"`
	DeletedAt       time.Time `json:"deleted_at"`
}

type TibetanSingingBowlMr struct {
	UniqueID uuid.UUID `json:"unique_id"`
	Uuid     uuid.UUID `json:"uuid"`
	// between 1-10
	StartMoodRating int16  `json:"start_mood_rating"`
	StartMood       string `json:"start_mood"`
	// between 1-10
	FinishMoodRating int16  `json:"finish_mood_rating"`
	FinishMood       string `json:"finish_mood"`
	// 0 = incomplete. 1 = complete
	SessionCompleted int16     `json:"session_completed"`
	StartedAt        time.Time `json:"started_at"`
	EndsAt           time.Time `json:"ends_at"`
	DeletedAt        time.Time `json:"deleted_at"`
}

type TummoBreathingMr struct {
	UniqueID uuid.UUID `json:"unique_id"`
	Uuid     uuid.UUID `json:"uuid"`
	// between 1-10
	StartMoodRating int16  `json:"start_mood_rating"`
	StartMood       string `json:"start_mood"`
	// between 1-10
	FinishMoodRating int16  `json:"finish_mood_rating"`
	FinishMood       string `json:"finish_mood"`
	// 0 = incomplete. 1 = complete
	SessionCompleted int16     `json:"session_completed"`
	StartedAt        time.Time `json:"started_at"`
	EndsAt           time.Time `json:"ends_at"`
	DeletedAt        time.Time `json:"deleted_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Email     string    `json:"email"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Gender    string    `json:"gender"`
	BirthDate time.Time `json:"birth_date"`
	Country   string    `json:"country"`
	// 1 = yes. 0 = no
	IsMrUser int16 `json:"is_mr_user"`
	// 1 = yes. 0 = no
	IsMobileUser      int16     `json:"is_mobile_user"`
	HashedPassword    string    `json:"hashed_password"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	Goals             string    `json:"goals"`
	CreatedAt         time.Time `json:"created_at"`
	DeletedAt         time.Time `json:"deleted_at"`
}

type UserEmail struct {
	UniqueId        uuid.UUID     `json:"unique_id"`
	Email     string    `json:"email"`
	Language  string    `json:"language"`
	ChakraInfo string    `json:"chakra_info"`
	CreatedAt time.Time `json:"created_at"`
	DeletedAt time.Time `json:"deleted_at"`
}
type UsersProfileMobile struct {
	UserID               int64     `json:"user_id"`
	TotalTimeSpentInMins int64     `json:"total_time_spent_in_mins"`
	DeletedAt            time.Time `json:"deleted_at"`
}

type UsersProfileMr struct {
	UserID               int64     `json:"user_id"`
	TotalTimeSpentInMins int64     `json:"total_time_spent_in_mins"`
	DeletedAt            time.Time `json:"deleted_at"`
}

type ChakraTestResult struct {
	UniqueId     uuid.UUID `json:"unique_id"`
	Email        string    `json:"email"`
	ChakraName   string    `json:"chakra_name"`
	ChakraScore  int32     `json:"chakra_score"`
	ChakraStatus string    `json:"chakra_status"`
	CreatedAt    time.Time `json:"created_at"`
	DeletedAt    time.Time `json:"deleted_at"`
}

type EmailRegistrations struct {
	UniqueId     uuid.UUID      `json:"unique_id"`
	Email        string         `json:"email"`
	Language     string         `json:"language"`
	UniqueCode   string         `json:"unique_code"`
	ChakraInfo   sql.NullString `json:"chakra_info"`
	ChakraReport sql.NullString `json:"chakra_report"`
	IP           string         `json:"ip"`
	Country      string         `json:"country"`
	CreatedAt    time.Time      `json:"created_at"`
	DeletedAt    time.Time      `json:"deleted_at"`
}

type ChakraBracelet struct {
	Chakra      sql.NullString `json:"chakra"` // 改为 sql.NullString
	Name        string         `json:"name"`
	ImageUrl    string         `json:"image_url"`
	ProductLink string         `json:"product_link"`
	Type        int32          `json:"type"`
	CreatedAt   time.Time      `json:"created_at"`
	DeletedAt   time.Time      `json:"deleted_at"`
}

type ChakraTestOptionAnswers struct {
	UniqueId uuid.UUID `json:"unique_id"`
	Email    string    `json:"email"`
	UniqueCode string    `json:"unique_code"`
	Question string    `json:"question"`
	Answer   string    `json:"answer"`
	CreatedAt time.Time `json:"created_at"`
	DeletedAt time.Time `json:"deleted_at"`
}
