// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package db

import (
	"context"
	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createUserEmail = `-- name: CreateUserEmail :one
INSERT INTO email_registrations  (
  unique_id,
  email,
  chakra_info,
  language,
  unique_code,
  ip,
  country
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING unique_id, email, chakra_info, language, unique_code, ip, country, created_at, deleted_at
`

type CreateUserEmailParams struct {
	UniqueId   uuid.UUID `json:"unique_id"`
	Email      string    `json:"email"`
	ChakraInfo string    `json:"chakra_info"`
	Language   string    `json:"language"`
	UniqueCode string    `json:"unique_code"`
	IP         string    `json:"ip"`
	Country    string    `json:"country"`
}

func (q *Queries) CreateUserEmail(ctx context.Context, arg CreateUserEmailParams) (EmailRegistrations, error) {
	row := q.db.QueryRowContext(ctx, createUserEmail,
		arg.UniqueId,
		arg.Email,
		arg.ChakraInfo,
		arg.Language,
		arg.UniqueCode,
		arg.IP,
		arg.Country,
	)
	var i EmailRegistrations
	err := row.Scan(
		&i.UniqueId,
		&i.Email,
		&i.ChakraInfo,
		&i.Language,
		&i.UniqueCode,
		&i.IP,
		&i.Country,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChakraTestResults = `-- name: GetChakraTestResults :many
SELECT unique_id, email, chakra_name, chakra_score, chakra_status, created_at
FROM chakra_test_results
WHERE email = $1 AND deleted_at = '0001-01-01 00:00:00Z'
ORDER BY created_at DESC; 
`

type GetChakraTestResultsParams struct {
	Email string `json:"email"`
}

func (q *Queries) GetChakraTestResults(ctx context.Context, arg GetChakraTestResultsParams) ([]ChakraTestResult, error) {
	rows, err := q.db.QueryContext(ctx, getChakraTestResults, arg.Email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChakraTestResult{}
	for rows.Next() {
		var i ChakraTestResult
		if err := rows.Scan(
			&i.UniqueId,
			&i.Email,
			&i.ChakraName,
			&i.ChakraScore,
			&i.ChakraStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, nil
}



const createChakraTestResult = `-- name: CreateChakraTestResult :one
INSERT INTO chakra_test_results (
    unique_id,
    email,
    chakra_name,
    chakra_score,
    chakra_status
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING *; 
`

type CreateChakraTestResultParams struct {
	UniqueId     uuid.UUID `json:"unique_id"`
	Email        string    `json:"email"`
	ChakraName   string    `json:"chakra_name"`
	ChakraScore  int32     `json:"chakra_score"`
	ChakraStatus string    `json:"chakra_status"`
}

func (q *Queries) CreateChakraTestResult(ctx context.Context, arg CreateChakraTestResultParams) (ChakraTestResult, error) {
	row := q.db.QueryRowContext(ctx, createChakraTestResult,
		arg.UniqueId,
		arg.Email,
		arg.ChakraName,
		arg.ChakraScore,
		arg.ChakraStatus,
	)
	var i ChakraTestResult
	err := row.Scan(
		&i.UniqueId,
		&i.Email,
		&i.ChakraName,
		&i.ChakraScore,
		&i.ChakraStatus,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getByEmail = `-- name: GetByEmail :one
SELECT id, email, created_at, deleted_at FROM users
WHERE email = $1
`

func (q *Queries) GetByEmail(ctx context.Context, email string) (EmailRegistrations, error) {
	row := q.db.QueryRowContext(ctx, getByEmail, email)
	var i EmailRegistrations
	err := row.Scan(
		&i.UniqueId,
		&i.Email,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}


const getLatestEmailRegistration = `-- name: GetLatestEmailRegistration :one
SELECT unique_id, email, unique_code, created_at, deleted_at FROM email_registrations
WHERE email = $1
ORDER BY created_at DESC
LIMIT 1;
`

func (q *Queries) GetLatestEmailRegistration(ctx context.Context, email string) (EmailRegistrations, error) {
	row := q.db.QueryRowContext(ctx, getLatestEmailRegistration, email)
	var i EmailRegistrations
	err := row.Scan(
		&i.UniqueId,
		&i.Email,
		&i.ChakraReport,
		&i.UniqueCode,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}


const updateChakraReportByUniqueId = `-- name: UpdateChakraReportByUniqueId :exec
UPDATE email_registrations
SET chakra_report = $1
WHERE unique_id = $2
`

func (q *Queries) UpdateChakraReportByUniqueId(ctx context.Context, chakraReport string, uniqueId uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateChakraReportByUniqueId, chakraReport, uniqueId)
	return err
}


const getEmailRegistrationByTestNum = `-- name: GetEmailRegistrationByTestNum :one
SELECT unique_id, email, language, chakra_info, chakra_report, unique_code, created_at, deleted_at
FROM email_registrations
WHERE email = $1
ORDER BY created_at
OFFSET $2 LIMIT 1;
`

func (q *Queries) GetEmailRegistrationByTestNum(ctx context.Context, email string, testNum int) (EmailRegistrations, error) {
	row := q.db.QueryRowContext(ctx, getEmailRegistrationByTestNum, email, testNum)
	var i EmailRegistrations
	err := row.Scan(
		&i.UniqueId,
		&i.Email,
		&i.Language,
		&i.ChakraInfo,
		&i.ChakraReport,
		&i.UniqueCode,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}


const getChakraBracelet = `
WITH custom_bracelets AS (
    SELECT chakra, name, image_url, product_link, type, created_at, deleted_at
    FROM chakra_bracelet 
    WHERE chakra = ANY($1) AND type = 0
    ORDER BY created_at DESC
),
random_bracelets AS (
    SELECT chakra, name, image_url, product_link, type, created_at, deleted_at
    FROM chakra_bracelet 
    WHERE type = 1
    ORDER BY RANDOM()
    LIMIT 2
)
SELECT * FROM random_bracelets	
UNION ALL
SELECT * FROM custom_bracelets;
`


func (q *Queries) GetChakraBracelet(ctx context.Context, chakras []string) ([]ChakraBracelet, error) {
	rows, err := q.db.QueryContext(ctx, getChakraBracelet, pq.Array(chakras))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	
	var items []ChakraBracelet
	for rows.Next() {
		var i ChakraBracelet
		if err := rows.Scan(
			&i.Chakra,
			&i.Name,
			&i.ImageUrl,
			&i.ProductLink,
			&i.Type,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err = rows.Close(); err != nil {
		return nil, err
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}


const getReportByCode = `-- name: GetReportByCode :one
SELECT unique_id, email, chakra_info, chakra_report, language, unique_code, created_at, deleted_at
FROM email_registrations
WHERE unique_code = $1 AND deleted_at = '0001-01-01 00:00:00+00'
LIMIT 1;
`	

func (q *Queries) GetReportByCode(ctx context.Context, code string) (EmailRegistrations, error) {
	row := q.db.QueryRowContext(ctx, getReportByCode, code)
	var i EmailRegistrations
	err := row.Scan(
		&i.UniqueId,
		&i.Email,
		&i.ChakraInfo,
		&i.ChakraReport,
		&i.Language,
		&i.UniqueCode,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}


const createChakraTestOptionAnswersBatch = `-- name: CreateChakraTestOptionAnswersBatch :many
INSERT INTO chakra_test_option_answers (
    unique_id,
    email,
    unique_code,
    question,
    answer
)
SELECT unnest($1::uuid[]), unnest($2::text[]), unnest($3::text[]), unnest($4::text[]), unnest($5::text[])
RETURNING *; 
`


type CreateChakraTestOptionAnswersBatchParams struct {
	UniqueIds []uuid.UUID `json:"unique_ids"`
	Emails    []string    `json:"emails"`
	UniqueCodes []string    `json:"unique_codes"`
	Questions []string    `json:"questions"`
	Answers   []string    `json:"answers"`
}

func (q *Queries) CreateChakraTestOptionAnswersBatch(ctx context.Context, arg CreateChakraTestOptionAnswersBatchParams) (ChakraTestOptionAnswers, error) {
	row := q.db.QueryRowContext(ctx, createChakraTestOptionAnswersBatch,
		pq.Array(arg.UniqueIds),
		pq.Array(arg.Emails),
		pq.Array(arg.UniqueCodes),
		pq.Array(arg.Questions),
		pq.Array(arg.Answers),
	)
	var i ChakraTestOptionAnswers
	err := row.Scan(
		&i.UniqueId,
		&i.Email,
		&i.UniqueCode,
		&i.Question,
		&i.Answer,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}














