// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUserEmail = `-- name: CreateUserEmail :one
INSERT INTO email_registrations  (
  unique_id,
  email,
  chakra_info	
) VALUES (
  $1, $2, $3
)
RETURNING unique_id, email, chakra_info, created_at, deleted_at
`

type CreateUserEmailParams struct {
	UniqueId       uuid.UUID `json:"unique_id"`
	Email          string    `json:"email"`
	ChakraInfo     string    `json:"chakra_info"`
}

func (q *Queries) CreateUserEmail(ctx context.Context, arg CreateUserEmailParams) (UserEmail, error) {
	row := q.db.QueryRowContext(ctx, createUserEmail,
		arg.UniqueId,
		arg.Email,
		arg.ChakraInfo,
	)
	var i UserEmail
	err := row.Scan(
		&i.UniqueId,
		&i.Email,
		&i.ChakraInfo,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChakraTestResults = `-- name: GetChakraTestResults :many
SELECT unique_id, email, chakra_name, chakra_score, chakra_status, created_at
FROM chakra_test_results
WHERE email = $1 AND deleted_at = '0001-01-01 00:00:00Z'
ORDER BY created_at DESC; 
`

type GetChakraTestResultsParams struct {
	Email string `json:"email"`
}

func (q *Queries) GetChakraTestResults(ctx context.Context, arg GetChakraTestResultsParams) ([]ChakraTestResult, error) {
	rows, err := q.db.QueryContext(ctx, getChakraTestResults, arg.Email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChakraTestResult{}
	for rows.Next() {
		var i ChakraTestResult
		if err := rows.Scan(
			&i.UniqueId,
			&i.Email,
			&i.ChakraName,
			&i.ChakraScore,
			&i.ChakraStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, nil
}



const createChakraTestResult = `-- name: CreateChakraTestResult :one
INSERT INTO chakra_test_results (
    unique_id,
    email,
    chakra_name,
    chakra_score,
    chakra_status
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING *; 
`

type CreateChakraTestResultParams struct {
	UniqueId     uuid.UUID `json:"unique_id"`
	Email        string    `json:"email"`
	ChakraName   string    `json:"chakra_name"`
	ChakraScore  int32     `json:"chakra_score"`
	ChakraStatus string    `json:"chakra_status"`
}

func (q *Queries) CreateChakraTestResult(ctx context.Context, arg CreateChakraTestResultParams) (ChakraTestResult, error) {
	row := q.db.QueryRowContext(ctx, createChakraTestResult,
		arg.UniqueId,
		arg.Email,
		arg.ChakraName,
		arg.ChakraScore,
		arg.ChakraStatus,
	)
	var i ChakraTestResult
	err := row.Scan(
		&i.UniqueId,
		&i.Email,
		&i.ChakraName,
		&i.ChakraScore,
		&i.ChakraStatus,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getByEmail = `-- name: GetByEmail :one
SELECT id, email, created_at, deleted_at FROM users
WHERE email = $1
`

func (q *Queries) GetByEmail(ctx context.Context, email string) (EmailRegistrations, error) {
	row := q.db.QueryRowContext(ctx, getByEmail, email)
	var i EmailRegistrations
	err := row.Scan(
		&i.UniqueId,
		&i.Email,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}


const getLatestEmailRegistration = `-- name: GetLatestEmailRegistration :one
SELECT unique_id, email, chakra_report, created_at, deleted_at FROM email_registrations
WHERE email = $1
ORDER BY created_at DESC
LIMIT 1;
`

func (q *Queries) GetLatestEmailRegistration(ctx context.Context, email string) (EmailRegistrations, error) {
	row := q.db.QueryRowContext(ctx, getLatestEmailRegistration, email)
	var i EmailRegistrations
	err := row.Scan(
		&i.UniqueId,
		&i.Email,
		&i.ChakraReport,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}


const updateChakraReportByUniqueId = `-- name: UpdateChakraReportByUniqueId :exec
UPDATE email_registrations
SET chakra_report = $1
WHERE unique_id = $2
`

func (q *Queries) UpdateChakraReportByUniqueId(ctx context.Context, chakraReport string, uniqueId uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateChakraReportByUniqueId, chakraReport, uniqueId)
	return err
}


const getEmailRegistrationByTestNum = `-- name: GetEmailRegistrationByTestNum :one
SELECT unique_id, email, chakra_info, chakra_report, created_at, deleted_at
FROM email_registrations
WHERE email = $1
ORDER BY created_at
OFFSET $2 LIMIT 1;
`

func (q *Queries) GetEmailRegistrationByTestNum(ctx context.Context, email string, testNum int) (EmailRegistrations, error) {
	row := q.db.QueryRowContext(ctx, getEmailRegistrationByTestNum, email, testNum)
	var i EmailRegistrations
	err := row.Scan(
		&i.UniqueId,
		&i.Email,
		&i.ChakraInfo,
		&i.ChakraReport,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

