// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateChakraTestOptionAnswersBatch(ctx context.Context, arg CreateChakraTestOptionAnswersBatchParams) ([]ChakraTestOptionAnswer, error)
	CreateChakraTestResults(ctx context.Context, arg CreateChakraTestResultsParams) (ChakraTestResult, error)
	CreateSessionLog(ctx context.Context, arg CreateSessionLogParams) (SessionLog, error)
	CreateTibetanSingingBowlMr(ctx context.Context, arg CreateTibetanSingingBowlMrParams) (TibetanSingingBowlMr, error)
	CreateTummoBreathingMr(ctx context.Context, arg CreateTummoBreathingMrParams) (TummoBreathingMr, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserEmail(ctx context.Context, arg CreateUserEmailParams) (CreateUserEmailRow, error)
	CreateUserProfileMobile(ctx context.Context, userID int64) error
	CreateUserProfileMr(ctx context.Context, userID int64) error
	DeleteSessionLog(ctx context.Context, argUuid uuid.UUID) error
	DeleteUser(ctx context.Context, id int64) error
	GetByEmail(ctx context.Context, email string) (GetByEmailRow, error)
	GetChakraBracelet(ctx context.Context, chakras []string) ([]GetChakraBraceletRow, error)
	GetChakraTestResults(ctx context.Context, email string) ([]GetChakraTestResultsRow, error)
	GetEmailRegistrationByTestNum(ctx context.Context, arg GetEmailRegistrationByTestNumParams) (GetEmailRegistrationByTestNumRow, error)
	GetLatestEmailRegistration(ctx context.Context, email string) (GetLatestEmailRegistrationRow, error)
	GetReportByCode(ctx context.Context, uniqueCode string) (GetReportByCodeRow, error)
	GetSessionLogByUUID(ctx context.Context, argUuid uuid.UUID) (SessionLog, error)
	GetSessionsLogByUserId(ctx context.Context, userID int64) ([]SessionLog, error)
	GetSessionsLogByUserIdWithOffset(ctx context.Context, arg GetSessionsLogByUserIdWithOffsetParams) ([]SessionLog, error)
	GetTibetanSingingBowlMrByUniqueID(ctx context.Context, uniqueID uuid.UUID) (TibetanSingingBowlMr, error)
	GetTibetanSingingBowlMrByUserID(ctx context.Context, userID int64) ([]TibetanSingingBowlMr, error)
	GetTibetanSingingBowlMrByUuid(ctx context.Context, argUuid uuid.UUID) (TibetanSingingBowlMr, error)
	GetTummoBreathingMrByUniqueID(ctx context.Context, uniqueID uuid.UUID) (TummoBreathingMr, error)
	GetTummoBreathingMrByUserID(ctx context.Context, userID int64) ([]TummoBreathingMr, error)
	GetTummoBreathingMrByUuid(ctx context.Context, argUuid uuid.UUID) (TummoBreathingMr, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	GetUserIdFromSessionLogUuid(ctx context.Context, argUuid uuid.UUID) (int64, error)
	GetUserProfileMobileByUserId(ctx context.Context, userID int64) (UsersProfileMobile, error)
	GetUserProfileMobileTime(ctx context.Context, userID int64) (int64, error)
	GetUserProfileMrByUserId(ctx context.Context, userID int64) (UsersProfileMr, error)
	GetUserProfileMrTime(ctx context.Context, userID int64) (int64, error)
	GetUsersByCountry(ctx context.Context, country string) ([]User, error)
	SoftDeleteTibetanSingingBowlMrByUniqueID(ctx context.Context, uniqueID uuid.UUID) (TibetanSingingBowlMr, error)
	SoftDeleteTummoBreathingMrByUniqueID(ctx context.Context, uniqueID uuid.UUID) (TummoBreathingMr, error)
	UpdateTibetanSingingBowlMrByUniqueID(ctx context.Context, arg UpdateTibetanSingingBowlMrByUniqueIDParams) (TibetanSingingBowlMr, error)
	UpdateTibetanSingingBowlMrByUuid(ctx context.Context, arg UpdateTibetanSingingBowlMrByUuidParams) (TibetanSingingBowlMr, error)
	UpdateTibetanSingingBowlMrFinishingMoodByUuid(ctx context.Context, arg UpdateTibetanSingingBowlMrFinishingMoodByUuidParams) (TibetanSingingBowlMr, error)
	UpdateTibetanSingingBowlMrQuitByUuid(ctx context.Context, arg UpdateTibetanSingingBowlMrQuitByUuidParams) (TibetanSingingBowlMr, error)
	UpdateTibetanSingingBowlMrStartingMoodByUuid(ctx context.Context, arg UpdateTibetanSingingBowlMrStartingMoodByUuidParams) (TibetanSingingBowlMr, error)
	UpdateTummoBreathingMrByUniqueID(ctx context.Context, arg UpdateTummoBreathingMrByUniqueIDParams) (TummoBreathingMr, error)
	UpdateTummoBreathingMrByUuid(ctx context.Context, arg UpdateTummoBreathingMrByUuidParams) (TummoBreathingMr, error)
	UpdateTummoBreathingMrFinishingMoodByUuid(ctx context.Context, arg UpdateTummoBreathingMrFinishingMoodByUuidParams) (TummoBreathingMr, error)
	UpdateTummoBreathingMrQuitByUuid(ctx context.Context, arg UpdateTummoBreathingMrQuitByUuidParams) (TummoBreathingMr, error)
	UpdateTummoBreathingMrStartingMoodByUuid(ctx context.Context, arg UpdateTummoBreathingMrStartingMoodByUuidParams) (TummoBreathingMr, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserProfileMobilerTime(ctx context.Context, arg UpdateUserProfileMobilerTimeParams) error
	UpdateUserProfileMrTime(ctx context.Context, arg UpdateUserProfileMrTimeParams) error
}

var _ Querier = (*Queries)(nil)
