// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSessionLog(ctx context.Context, arg CreateSessionLogParams) (SessionLog, error)
	CreateTibetanSingingBowlMr(ctx context.Context, arg CreateTibetanSingingBowlMrParams) (TibetanSingingBowlMr, error)
	CreateTummoBreathingMr(ctx context.Context, arg CreateTummoBreathingMrParams) (TummoBreathingMr, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserProfileMobile(ctx context.Context, userID int64) error
	CreateUserProfileMr(ctx context.Context, userID int64) error
	DeleteSessionLog(ctx context.Context, argUuid uuid.UUID) error
	DeleteTibetanSingingBowlMrByUniqueID(ctx context.Context, uniqueID uuid.UUID) (TibetanSingingBowlMr, error)
	DeleteTummoBreathingMrByUniqueID(ctx context.Context, uniqueID uuid.UUID) (TummoBreathingMr, error)
	DeleteUser(ctx context.Context, id int64) error
	GetSessionLogByUUID(ctx context.Context, argUuid uuid.UUID) (SessionLog, error)
	GetSessionsLogByUserId(ctx context.Context, userID int64) ([]SessionLog, error)
	GetSessionsLogByUserIdWithOffset(ctx context.Context, arg GetSessionsLogByUserIdWithOffsetParams) ([]SessionLog, error)
	GetTibetanSingingBowlMrByUniqueID(ctx context.Context, uniqueID uuid.UUID) (TibetanSingingBowlMr, error)
	GetTibetanSingingBowlMrByUserID(ctx context.Context, userID int64) ([]TibetanSingingBowlMr, error)
	GetTibetanSingingBowlMrByUuid(ctx context.Context, argUuid uuid.UUID) (TibetanSingingBowlMr, error)
	GetTummoBreathingMrByUniqueID(ctx context.Context, uniqueID uuid.UUID) (TummoBreathingMr, error)
	GetTummoBreathingMrByUserID(ctx context.Context, userID int64) ([]TummoBreathingMr, error)
	GetTummoBreathingMrByUuid(ctx context.Context, argUuid uuid.UUID) (TummoBreathingMr, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	GetUserIdFromSessionLogUuid(ctx context.Context, argUuid uuid.UUID) (int64, error)
	GetUserProfileMobileByUserId(ctx context.Context, userID int64) (UsersProfileMobile, error)
	GetUserProfileMobileTime(ctx context.Context, userID int64) (int64, error)
	GetUserProfileMrByUserId(ctx context.Context, userID int64) (UsersProfileMr, error)
	GetUserProfileMrTime(ctx context.Context, userID int64) (int64, error)
	GetUsersByCountry(ctx context.Context, country string) ([]User, error)
	UpdateTibetanSingingBowlMrByUniqueID(ctx context.Context, arg UpdateTibetanSingingBowlMrByUniqueIDParams) (TibetanSingingBowlMr, error)
	UpdateTibetanSingingBowlMrByUuid(ctx context.Context, arg UpdateTibetanSingingBowlMrByUuidParams) (TibetanSingingBowlMr, error)
	UpdateTibetanSingingBowlMrFinishingMoodByUuid(ctx context.Context, arg UpdateTibetanSingingBowlMrFinishingMoodByUuidParams) (TibetanSingingBowlMr, error)
	UpdateTibetanSingingBowlMrQuitByUuid(ctx context.Context, arg UpdateTibetanSingingBowlMrQuitByUuidParams) error
	UpdateTibetanSingingBowlMrStartingMoodByUuid(ctx context.Context, arg UpdateTibetanSingingBowlMrStartingMoodByUuidParams) error
	UpdateTummoBreathingMrByUniqueID(ctx context.Context, arg UpdateTummoBreathingMrByUniqueIDParams) (TummoBreathingMr, error)
	UpdateTummoBreathingMrByUuid(ctx context.Context, arg UpdateTummoBreathingMrByUuidParams) (TummoBreathingMr, error)
	UpdateTummoBreathingMrFinishingMoodByUuid(ctx context.Context, arg UpdateTummoBreathingMrFinishingMoodByUuidParams) (TummoBreathingMr, error)
	UpdateTummoBreathingMrQuitByUuid(ctx context.Context, arg UpdateTummoBreathingMrQuitByUuidParams) error
	UpdateTummoBreathingMrStartingMoodByUuid(ctx context.Context, arg UpdateTummoBreathingMrStartingMoodByUuidParams) error
	UpdateUserProfileMobilerTime(ctx context.Context, arg UpdateUserProfileMobilerTimeParams) error
	UpdateUserProfileMrTime(ctx context.Context, arg UpdateUserProfileMrTimeParams) error
}

var _ Querier = (*Queries)(nil)
