// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessionLog.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSessionLog = `-- name: CreateSessionLog :one
INSERT INTO session_logs (
  user_id,
  session_type,
  session_platform
) VALUES (
  $1, $2, $3
)
RETURNING uuid, user_id, session_type, session_platform, created_at, deleted_at
`

type CreateSessionLogParams struct {
	UserID          int64  `json:"user_id"`
	SessionType     string `json:"session_type"`
	SessionPlatform string `json:"session_platform"`
}

func (q *Queries) CreateSessionLog(ctx context.Context, arg CreateSessionLogParams) (SessionLog, error) {
	row := q.db.QueryRowContext(ctx, createSessionLog, arg.UserID, arg.SessionType, arg.SessionPlatform)
	var i SessionLog
	err := row.Scan(
		&i.Uuid,
		&i.UserID,
		&i.SessionType,
		&i.SessionPlatform,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSessionLog = `-- name: DeleteSessionLog :exec
DELETE FROM session_logs
WHERE uuid = $1
`

func (q *Queries) DeleteSessionLog(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSessionLog, argUuid)
	return err
}

const getSessionLogByUUID = `-- name: GetSessionLogByUUID :one
SELECT uuid, user_id, session_type, session_platform, created_at, deleted_at FROM session_logs
WHERE uuid = $1
`

func (q *Queries) GetSessionLogByUUID(ctx context.Context, argUuid uuid.UUID) (SessionLog, error) {
	row := q.db.QueryRowContext(ctx, getSessionLogByUUID, argUuid)
	var i SessionLog
	err := row.Scan(
		&i.Uuid,
		&i.UserID,
		&i.SessionType,
		&i.SessionPlatform,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSessionsLogByUserId = `-- name: GetSessionsLogByUserId :many
SELECT uuid, user_id, session_type, session_platform, created_at, deleted_at FROM session_logs
WHERE user_id = $1
`

func (q *Queries) GetSessionsLogByUserId(ctx context.Context, userID int64) ([]SessionLog, error) {
	rows, err := q.db.QueryContext(ctx, getSessionsLogByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionLog{}
	for rows.Next() {
		var i SessionLog
		if err := rows.Scan(
			&i.Uuid,
			&i.UserID,
			&i.SessionType,
			&i.SessionPlatform,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionsLogByUserIdWithOffset = `-- name: GetSessionsLogByUserIdWithOffset :many
SELECT uuid, user_id, session_type, session_platform, created_at, deleted_at FROM session_logs
WHERE user_id = $1
LIMIT $2
OFFSET $3
`

type GetSessionsLogByUserIdWithOffsetParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetSessionsLogByUserIdWithOffset(ctx context.Context, arg GetSessionsLogByUserIdWithOffsetParams) ([]SessionLog, error) {
	rows, err := q.db.QueryContext(ctx, getSessionsLogByUserIdWithOffset, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionLog{}
	for rows.Next() {
		var i SessionLog
		if err := rows.Scan(
			&i.Uuid,
			&i.UserID,
			&i.SessionType,
			&i.SessionPlatform,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
