// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tibetanSingingBowlMr.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTibetanSingingBowlMr = `-- name: CreateTibetanSingingBowlMr :one
INSERT INTO tibetan_singing_bowl_mr (
  uuid,
  start_mood_rating,
  start_mood,
  finish_mood_rating,
  finish_mood,
  session_completed
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING unique_id, uuid, start_mood_rating, start_mood, finish_mood_rating, finish_mood, session_completed, started_at, ends_at, deleted_at
`

type CreateTibetanSingingBowlMrParams struct {
	Uuid             uuid.UUID `json:"uuid"`
	StartMoodRating  int16     `json:"start_mood_rating"`
	StartMood        string    `json:"start_mood"`
	FinishMoodRating int16     `json:"finish_mood_rating"`
	FinishMood       string    `json:"finish_mood"`
	SessionCompleted int16     `json:"session_completed"`
}

func (q *Queries) CreateTibetanSingingBowlMr(ctx context.Context, arg CreateTibetanSingingBowlMrParams) (TibetanSingingBowlMr, error) {
	row := q.db.QueryRowContext(ctx, createTibetanSingingBowlMr,
		arg.Uuid,
		arg.StartMoodRating,
		arg.StartMood,
		arg.FinishMoodRating,
		arg.FinishMood,
		arg.SessionCompleted,
	)
	var i TibetanSingingBowlMr
	err := row.Scan(
		&i.UniqueID,
		&i.Uuid,
		&i.StartMoodRating,
		&i.StartMood,
		&i.FinishMoodRating,
		&i.FinishMood,
		&i.SessionCompleted,
		&i.StartedAt,
		&i.EndsAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTibetanSingingBowlMrByUniqueID = `-- name: DeleteTibetanSingingBowlMrByUniqueID :one
DELETE FROM tibetan_singing_bowl_mr 
WHERE unique_id = $1
RETURNING unique_id, uuid, start_mood_rating, start_mood, finish_mood_rating, finish_mood, session_completed, started_at, ends_at, deleted_at
`

func (q *Queries) DeleteTibetanSingingBowlMrByUniqueID(ctx context.Context, uniqueID uuid.UUID) (TibetanSingingBowlMr, error) {
	row := q.db.QueryRowContext(ctx, deleteTibetanSingingBowlMrByUniqueID, uniqueID)
	var i TibetanSingingBowlMr
	err := row.Scan(
		&i.UniqueID,
		&i.Uuid,
		&i.StartMoodRating,
		&i.StartMood,
		&i.FinishMoodRating,
		&i.FinishMood,
		&i.SessionCompleted,
		&i.StartedAt,
		&i.EndsAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTibetanSingingBowlMrByUniqueID = `-- name: GetTibetanSingingBowlMrByUniqueID :one
SELECT unique_id, uuid, start_mood_rating, start_mood, finish_mood_rating, finish_mood, session_completed, started_at, ends_at, deleted_at 
FROM tibetan_singing_bowl_mr 
WHERE unique_id = $1
`

func (q *Queries) GetTibetanSingingBowlMrByUniqueID(ctx context.Context, uniqueID uuid.UUID) (TibetanSingingBowlMr, error) {
	row := q.db.QueryRowContext(ctx, getTibetanSingingBowlMrByUniqueID, uniqueID)
	var i TibetanSingingBowlMr
	err := row.Scan(
		&i.UniqueID,
		&i.Uuid,
		&i.StartMoodRating,
		&i.StartMood,
		&i.FinishMoodRating,
		&i.FinishMood,
		&i.SessionCompleted,
		&i.StartedAt,
		&i.EndsAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTibetanSingingBowlMrByUserID = `-- name: GetTibetanSingingBowlMrByUserID :many
SELECT 
  tbm.unique_id, tbm.uuid, tbm.start_mood_rating, tbm.start_mood, tbm.finish_mood_rating, tbm.finish_mood, tbm.session_completed, tbm.started_at, tbm.ends_at, tbm.deleted_at
FROM 
  tibetan_singing_bowl_mr AS tbm
JOIN 
  session_logs AS sl ON tbm.uuid = sl.uuid
WHERE 
  sl.user_id = $1
`

func (q *Queries) GetTibetanSingingBowlMrByUserID(ctx context.Context, userID int64) ([]TibetanSingingBowlMr, error) {
	rows, err := q.db.QueryContext(ctx, getTibetanSingingBowlMrByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TibetanSingingBowlMr{}
	for rows.Next() {
		var i TibetanSingingBowlMr
		if err := rows.Scan(
			&i.UniqueID,
			&i.Uuid,
			&i.StartMoodRating,
			&i.StartMood,
			&i.FinishMoodRating,
			&i.FinishMood,
			&i.SessionCompleted,
			&i.StartedAt,
			&i.EndsAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTibetanSingingBowlMrByUuid = `-- name: GetTibetanSingingBowlMrByUuid :one
SELECT unique_id, uuid, start_mood_rating, start_mood, finish_mood_rating, finish_mood, session_completed, started_at, ends_at, deleted_at 
FROM tibetan_singing_bowl_mr 
WHERE uuid = $1
`

func (q *Queries) GetTibetanSingingBowlMrByUuid(ctx context.Context, argUuid uuid.UUID) (TibetanSingingBowlMr, error) {
	row := q.db.QueryRowContext(ctx, getTibetanSingingBowlMrByUuid, argUuid)
	var i TibetanSingingBowlMr
	err := row.Scan(
		&i.UniqueID,
		&i.Uuid,
		&i.StartMoodRating,
		&i.StartMood,
		&i.FinishMoodRating,
		&i.FinishMood,
		&i.SessionCompleted,
		&i.StartedAt,
		&i.EndsAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTibetanSingingBowlMrByUniqueID = `-- name: UpdateTibetanSingingBowlMrByUniqueID :one
UPDATE tibetan_singing_bowl_mr
SET
  uuid = COALESCE($2, uuid),
  start_mood_rating = COALESCE($3, start_mood_rating),
  start_mood = COALESCE($4, start_mood),
  finish_mood_rating = COALESCE($5, finish_mood_rating),
  finish_mood = COALESCE($6, finish_mood),
  session_completed = COALESCE($7, session_completed),
  started_at = COALESCE($8, started_at),
  ends_at = COALESCE($9, ends_at),
  deleted_at = COALESCE($10, deleted_at)
WHERE unique_id = $1
RETURNING unique_id, uuid, start_mood_rating, start_mood, finish_mood_rating, finish_mood, session_completed, started_at, ends_at, deleted_at
`

type UpdateTibetanSingingBowlMrByUniqueIDParams struct {
	UniqueID         uuid.UUID `json:"unique_id"`
	Uuid             uuid.UUID `json:"uuid"`
	StartMoodRating  int16     `json:"start_mood_rating"`
	StartMood        string    `json:"start_mood"`
	FinishMoodRating int16     `json:"finish_mood_rating"`
	FinishMood       string    `json:"finish_mood"`
	SessionCompleted int16     `json:"session_completed"`
	StartedAt        time.Time `json:"started_at"`
	EndsAt           time.Time `json:"ends_at"`
	DeletedAt        time.Time `json:"deleted_at"`
}

func (q *Queries) UpdateTibetanSingingBowlMrByUniqueID(ctx context.Context, arg UpdateTibetanSingingBowlMrByUniqueIDParams) (TibetanSingingBowlMr, error) {
	row := q.db.QueryRowContext(ctx, updateTibetanSingingBowlMrByUniqueID,
		arg.UniqueID,
		arg.Uuid,
		arg.StartMoodRating,
		arg.StartMood,
		arg.FinishMoodRating,
		arg.FinishMood,
		arg.SessionCompleted,
		arg.StartedAt,
		arg.EndsAt,
		arg.DeletedAt,
	)
	var i TibetanSingingBowlMr
	err := row.Scan(
		&i.UniqueID,
		&i.Uuid,
		&i.StartMoodRating,
		&i.StartMood,
		&i.FinishMoodRating,
		&i.FinishMood,
		&i.SessionCompleted,
		&i.StartedAt,
		&i.EndsAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTibetanSingingBowlMrByUuid = `-- name: UpdateTibetanSingingBowlMrByUuid :one
UPDATE tibetan_singing_bowl_mr
SET
  start_mood_rating = COALESCE($2, start_mood_rating),
  start_mood = COALESCE($3, start_mood),
  finish_mood_rating = COALESCE($4, finish_mood_rating),
  finish_mood = COALESCE($5, finish_mood),
  session_completed = COALESCE($6, session_completed),
  started_at = COALESCE($7, started_at),
  ends_at = COALESCE($8, ends_at),
  deleted_at = COALESCE($9, deleted_at)
WHERE uuid = $1
RETURNING unique_id, uuid, start_mood_rating, start_mood, finish_mood_rating, finish_mood, session_completed, started_at, ends_at, deleted_at
`

type UpdateTibetanSingingBowlMrByUuidParams struct {
	Uuid             uuid.UUID `json:"uuid"`
	StartMoodRating  int16     `json:"start_mood_rating"`
	StartMood        string    `json:"start_mood"`
	FinishMoodRating int16     `json:"finish_mood_rating"`
	FinishMood       string    `json:"finish_mood"`
	SessionCompleted int16     `json:"session_completed"`
	StartedAt        time.Time `json:"started_at"`
	EndsAt           time.Time `json:"ends_at"`
	DeletedAt        time.Time `json:"deleted_at"`
}

func (q *Queries) UpdateTibetanSingingBowlMrByUuid(ctx context.Context, arg UpdateTibetanSingingBowlMrByUuidParams) (TibetanSingingBowlMr, error) {
	row := q.db.QueryRowContext(ctx, updateTibetanSingingBowlMrByUuid,
		arg.Uuid,
		arg.StartMoodRating,
		arg.StartMood,
		arg.FinishMoodRating,
		arg.FinishMood,
		arg.SessionCompleted,
		arg.StartedAt,
		arg.EndsAt,
		arg.DeletedAt,
	)
	var i TibetanSingingBowlMr
	err := row.Scan(
		&i.UniqueID,
		&i.Uuid,
		&i.StartMoodRating,
		&i.StartMood,
		&i.FinishMoodRating,
		&i.FinishMood,
		&i.SessionCompleted,
		&i.StartedAt,
		&i.EndsAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTibetanSingingBowlMrFinishingMoodByUuid = `-- name: UpdateTibetanSingingBowlMrFinishingMoodByUuid :one
UPDATE tibetan_singing_bowl_mr
SET
 finish_mood_rating = COALESCE($2, finish_mood_rating),
  finish_mood = COALESCE($3, finish_mood),
  session_completed = COALESCE($4, session_completed),
  ends_at = COALESCE($5, ends_at)
WHERE uuid = $1
RETURNING unique_id, uuid, start_mood_rating, start_mood, finish_mood_rating, finish_mood, session_completed, started_at, ends_at, deleted_at
`

type UpdateTibetanSingingBowlMrFinishingMoodByUuidParams struct {
	Uuid             uuid.UUID `json:"uuid"`
	FinishMoodRating int16     `json:"finish_mood_rating"`
	FinishMood       string    `json:"finish_mood"`
	SessionCompleted int16     `json:"session_completed"`
	EndsAt           time.Time `json:"ends_at"`
}

func (q *Queries) UpdateTibetanSingingBowlMrFinishingMoodByUuid(ctx context.Context, arg UpdateTibetanSingingBowlMrFinishingMoodByUuidParams) (TibetanSingingBowlMr, error) {
	row := q.db.QueryRowContext(ctx, updateTibetanSingingBowlMrFinishingMoodByUuid,
		arg.Uuid,
		arg.FinishMoodRating,
		arg.FinishMood,
		arg.SessionCompleted,
		arg.EndsAt,
	)
	var i TibetanSingingBowlMr
	err := row.Scan(
		&i.UniqueID,
		&i.Uuid,
		&i.StartMoodRating,
		&i.StartMood,
		&i.FinishMoodRating,
		&i.FinishMood,
		&i.SessionCompleted,
		&i.StartedAt,
		&i.EndsAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTibetanSingingBowlMrQuitByUuid = `-- name: UpdateTibetanSingingBowlMrQuitByUuid :exec
UPDATE tibetan_singing_bowl_mr
SET
  ends_at = COALESCE($2, ends_at)
WHERE uuid = $1
RETURNING unique_id, uuid, start_mood_rating, start_mood, finish_mood_rating, finish_mood, session_completed, started_at, ends_at, deleted_at
`

type UpdateTibetanSingingBowlMrQuitByUuidParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	EndsAt time.Time `json:"ends_at"`
}

func (q *Queries) UpdateTibetanSingingBowlMrQuitByUuid(ctx context.Context, arg UpdateTibetanSingingBowlMrQuitByUuidParams) error {
	_, err := q.db.ExecContext(ctx, updateTibetanSingingBowlMrQuitByUuid, arg.Uuid, arg.EndsAt)
	return err
}

const updateTibetanSingingBowlMrStartingMoodByUuid = `-- name: UpdateTibetanSingingBowlMrStartingMoodByUuid :exec
UPDATE tibetan_singing_bowl_mr
SET
  start_mood_rating = COALESCE($2, start_mood_rating),
  start_mood = COALESCE($3, start_mood)
WHERE uuid = $1
RETURNING unique_id, uuid, start_mood_rating, start_mood, finish_mood_rating, finish_mood, session_completed, started_at, ends_at, deleted_at
`

type UpdateTibetanSingingBowlMrStartingMoodByUuidParams struct {
	Uuid            uuid.UUID `json:"uuid"`
	StartMoodRating int16     `json:"start_mood_rating"`
	StartMood       string    `json:"start_mood"`
}

func (q *Queries) UpdateTibetanSingingBowlMrStartingMoodByUuid(ctx context.Context, arg UpdateTibetanSingingBowlMrStartingMoodByUuidParams) error {
	_, err := q.db.ExecContext(ctx, updateTibetanSingingBowlMrStartingMoodByUuid, arg.Uuid, arg.StartMoodRating, arg.StartMood)
	return err
}
