// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tummoBreathingMr.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTummoBreathingMr = `-- name: CreateTummoBreathingMr :one
INSERT INTO tummo_breathing_mr (
  uuid,
  start_mood_rating,
  start_mood,
  finish_mood_rating,
  finish_mood,
  session_completed
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING unique_id, uuid, start_mood_rating, start_mood, finish_mood_rating, finish_mood, session_completed, started_at, ends_at, deleted_at
`

type CreateTummoBreathingMrParams struct {
	Uuid             uuid.UUID `json:"uuid"`
	StartMoodRating  int16     `json:"start_mood_rating"`
	StartMood        string    `json:"start_mood"`
	FinishMoodRating int16     `json:"finish_mood_rating"`
	FinishMood       string    `json:"finish_mood"`
	SessionCompleted int16     `json:"session_completed"`
}

func (q *Queries) CreateTummoBreathingMr(ctx context.Context, arg CreateTummoBreathingMrParams) (TummoBreathingMr, error) {
	row := q.db.QueryRowContext(ctx, createTummoBreathingMr,
		arg.Uuid,
		arg.StartMoodRating,
		arg.StartMood,
		arg.FinishMoodRating,
		arg.FinishMood,
		arg.SessionCompleted,
	)
	var i TummoBreathingMr
	err := row.Scan(
		&i.UniqueID,
		&i.Uuid,
		&i.StartMoodRating,
		&i.StartMood,
		&i.FinishMoodRating,
		&i.FinishMood,
		&i.SessionCompleted,
		&i.StartedAt,
		&i.EndsAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTummoBreathingMrByUniqueID = `-- name: GetTummoBreathingMrByUniqueID :one
SELECT unique_id, uuid, start_mood_rating, start_mood, finish_mood_rating, finish_mood, session_completed, started_at, ends_at, deleted_at 
FROM tummo_breathing_mr 
WHERE unique_id = $1
`

func (q *Queries) GetTummoBreathingMrByUniqueID(ctx context.Context, uniqueID uuid.UUID) (TummoBreathingMr, error) {
	row := q.db.QueryRowContext(ctx, getTummoBreathingMrByUniqueID, uniqueID)
	var i TummoBreathingMr
	err := row.Scan(
		&i.UniqueID,
		&i.Uuid,
		&i.StartMoodRating,
		&i.StartMood,
		&i.FinishMoodRating,
		&i.FinishMood,
		&i.SessionCompleted,
		&i.StartedAt,
		&i.EndsAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTummoBreathingMrByUserID = `-- name: GetTummoBreathingMrByUserID :many
SELECT 
  tbm.unique_id, tbm.uuid, tbm.start_mood_rating, tbm.start_mood, tbm.finish_mood_rating, tbm.finish_mood, tbm.session_completed, tbm.started_at, tbm.ends_at, tbm.deleted_at
FROM 
  tummo_breathing_mr AS tbm
JOIN 
  session_logs AS sl ON tbm.uuid = sl.uuid
WHERE 
  sl.user_id = $1
`

func (q *Queries) GetTummoBreathingMrByUserID(ctx context.Context, userID int64) ([]TummoBreathingMr, error) {
	rows, err := q.db.QueryContext(ctx, getTummoBreathingMrByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TummoBreathingMr{}
	for rows.Next() {
		var i TummoBreathingMr
		if err := rows.Scan(
			&i.UniqueID,
			&i.Uuid,
			&i.StartMoodRating,
			&i.StartMood,
			&i.FinishMoodRating,
			&i.FinishMood,
			&i.SessionCompleted,
			&i.StartedAt,
			&i.EndsAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTummoBreathingMrByUuid = `-- name: GetTummoBreathingMrByUuid :one
SELECT unique_id, uuid, start_mood_rating, start_mood, finish_mood_rating, finish_mood, session_completed, started_at, ends_at, deleted_at 
FROM tummo_breathing_mr 
WHERE uuid = $1
`

func (q *Queries) GetTummoBreathingMrByUuid(ctx context.Context, argUuid uuid.UUID) (TummoBreathingMr, error) {
	row := q.db.QueryRowContext(ctx, getTummoBreathingMrByUuid, argUuid)
	var i TummoBreathingMr
	err := row.Scan(
		&i.UniqueID,
		&i.Uuid,
		&i.StartMoodRating,
		&i.StartMood,
		&i.FinishMoodRating,
		&i.FinishMood,
		&i.SessionCompleted,
		&i.StartedAt,
		&i.EndsAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteTummoBreathingMrByUniqueID = `-- name: SoftDeleteTummoBreathingMrByUniqueID :one
UPDATE tummo_breathing_mr 
SET deleted_at = NOW()
WHERE unique_id = $1 AND (deleted_at IS NULL OR deleted_at = '0001-01-01 00:00:00Z')
RETURNING unique_id, uuid, start_mood_rating, start_mood, finish_mood_rating, finish_mood, session_completed, started_at, ends_at, deleted_at
`

func (q *Queries) SoftDeleteTummoBreathingMrByUniqueID(ctx context.Context, uniqueID uuid.UUID) (TummoBreathingMr, error) {
	row := q.db.QueryRowContext(ctx, softDeleteTummoBreathingMrByUniqueID, uniqueID)
	var i TummoBreathingMr
	err := row.Scan(
		&i.UniqueID,
		&i.Uuid,
		&i.StartMoodRating,
		&i.StartMood,
		&i.FinishMoodRating,
		&i.FinishMood,
		&i.SessionCompleted,
		&i.StartedAt,
		&i.EndsAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTummoBreathingMrByUniqueID = `-- name: UpdateTummoBreathingMrByUniqueID :one
UPDATE tummo_breathing_mr
SET
  uuid = COALESCE($2, uuid),
  start_mood_rating = COALESCE($3, start_mood_rating),
  start_mood = COALESCE($4, start_mood),
  finish_mood_rating = COALESCE($5, finish_mood_rating),
  finish_mood = COALESCE($6, finish_mood),
  session_completed = COALESCE($7, session_completed),
  started_at = COALESCE($8, started_at),
  ends_at = COALESCE($9, ends_at),
  deleted_at = COALESCE($10, deleted_at)
WHERE unique_id = $1
RETURNING unique_id, uuid, start_mood_rating, start_mood, finish_mood_rating, finish_mood, session_completed, started_at, ends_at, deleted_at
`

type UpdateTummoBreathingMrByUniqueIDParams struct {
	UniqueID         uuid.UUID `json:"unique_id"`
	Uuid             uuid.UUID `json:"uuid"`
	StartMoodRating  int16     `json:"start_mood_rating"`
	StartMood        string    `json:"start_mood"`
	FinishMoodRating int16     `json:"finish_mood_rating"`
	FinishMood       string    `json:"finish_mood"`
	SessionCompleted int16     `json:"session_completed"`
	StartedAt        time.Time `json:"started_at"`
	EndsAt           time.Time `json:"ends_at"`
	DeletedAt        time.Time `json:"deleted_at"`
}

func (q *Queries) UpdateTummoBreathingMrByUniqueID(ctx context.Context, arg UpdateTummoBreathingMrByUniqueIDParams) (TummoBreathingMr, error) {
	row := q.db.QueryRowContext(ctx, updateTummoBreathingMrByUniqueID,
		arg.UniqueID,
		arg.Uuid,
		arg.StartMoodRating,
		arg.StartMood,
		arg.FinishMoodRating,
		arg.FinishMood,
		arg.SessionCompleted,
		arg.StartedAt,
		arg.EndsAt,
		arg.DeletedAt,
	)
	var i TummoBreathingMr
	err := row.Scan(
		&i.UniqueID,
		&i.Uuid,
		&i.StartMoodRating,
		&i.StartMood,
		&i.FinishMoodRating,
		&i.FinishMood,
		&i.SessionCompleted,
		&i.StartedAt,
		&i.EndsAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTummoBreathingMrByUuid = `-- name: UpdateTummoBreathingMrByUuid :one
UPDATE tummo_breathing_mr
SET
  start_mood_rating = COALESCE($2, start_mood_rating),
  start_mood = COALESCE($3, start_mood),
  finish_mood_rating = COALESCE($4, finish_mood_rating),
  finish_mood = COALESCE($5, finish_mood),
  session_completed = COALESCE($6, session_completed),
  started_at = COALESCE($7, started_at),
  ends_at = COALESCE($8, ends_at),
  deleted_at = COALESCE($9, deleted_at)
WHERE uuid = $1
RETURNING unique_id, uuid, start_mood_rating, start_mood, finish_mood_rating, finish_mood, session_completed, started_at, ends_at, deleted_at
`

type UpdateTummoBreathingMrByUuidParams struct {
	Uuid             uuid.UUID `json:"uuid"`
	StartMoodRating  int16     `json:"start_mood_rating"`
	StartMood        string    `json:"start_mood"`
	FinishMoodRating int16     `json:"finish_mood_rating"`
	FinishMood       string    `json:"finish_mood"`
	SessionCompleted int16     `json:"session_completed"`
	StartedAt        time.Time `json:"started_at"`
	EndsAt           time.Time `json:"ends_at"`
	DeletedAt        time.Time `json:"deleted_at"`
}

func (q *Queries) UpdateTummoBreathingMrByUuid(ctx context.Context, arg UpdateTummoBreathingMrByUuidParams) (TummoBreathingMr, error) {
	row := q.db.QueryRowContext(ctx, updateTummoBreathingMrByUuid,
		arg.Uuid,
		arg.StartMoodRating,
		arg.StartMood,
		arg.FinishMoodRating,
		arg.FinishMood,
		arg.SessionCompleted,
		arg.StartedAt,
		arg.EndsAt,
		arg.DeletedAt,
	)
	var i TummoBreathingMr
	err := row.Scan(
		&i.UniqueID,
		&i.Uuid,
		&i.StartMoodRating,
		&i.StartMood,
		&i.FinishMoodRating,
		&i.FinishMood,
		&i.SessionCompleted,
		&i.StartedAt,
		&i.EndsAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTummoBreathingMrFinishingMoodByUuid = `-- name: UpdateTummoBreathingMrFinishingMoodByUuid :one
UPDATE tummo_breathing_mr
SET
 finish_mood_rating = COALESCE($2, finish_mood_rating),
  finish_mood = COALESCE($3, finish_mood),
  session_completed = COALESCE($4, session_completed),
  ends_at = COALESCE($5, ends_at)
WHERE uuid = $1
RETURNING unique_id, uuid, start_mood_rating, start_mood, finish_mood_rating, finish_mood, session_completed, started_at, ends_at, deleted_at
`

type UpdateTummoBreathingMrFinishingMoodByUuidParams struct {
	Uuid             uuid.UUID `json:"uuid"`
	FinishMoodRating int16     `json:"finish_mood_rating"`
	FinishMood       string    `json:"finish_mood"`
	SessionCompleted int16     `json:"session_completed"`
	EndsAt           time.Time `json:"ends_at"`
}

func (q *Queries) UpdateTummoBreathingMrFinishingMoodByUuid(ctx context.Context, arg UpdateTummoBreathingMrFinishingMoodByUuidParams) (TummoBreathingMr, error) {
	row := q.db.QueryRowContext(ctx, updateTummoBreathingMrFinishingMoodByUuid,
		arg.Uuid,
		arg.FinishMoodRating,
		arg.FinishMood,
		arg.SessionCompleted,
		arg.EndsAt,
	)
	var i TummoBreathingMr
	err := row.Scan(
		&i.UniqueID,
		&i.Uuid,
		&i.StartMoodRating,
		&i.StartMood,
		&i.FinishMoodRating,
		&i.FinishMood,
		&i.SessionCompleted,
		&i.StartedAt,
		&i.EndsAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTummoBreathingMrQuitByUuid = `-- name: UpdateTummoBreathingMrQuitByUuid :exec
UPDATE tummo_breathing_mr
SET
  ends_at = COALESCE($2, ends_at)
WHERE uuid = $1
RETURNING unique_id, uuid, start_mood_rating, start_mood, finish_mood_rating, finish_mood, session_completed, started_at, ends_at, deleted_at
`

type UpdateTummoBreathingMrQuitByUuidParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	EndsAt time.Time `json:"ends_at"`
}

func (q *Queries) UpdateTummoBreathingMrQuitByUuid(ctx context.Context, arg UpdateTummoBreathingMrQuitByUuidParams) error {
	_, err := q.db.ExecContext(ctx, updateTummoBreathingMrQuitByUuid, arg.Uuid, arg.EndsAt)
	return err
}

const updateTummoBreathingMrStartingMoodByUuid = `-- name: UpdateTummoBreathingMrStartingMoodByUuid :exec
UPDATE tummo_breathing_mr
SET
  start_mood_rating = COALESCE($2, start_mood_rating),
  start_mood = COALESCE($3, start_mood)
WHERE uuid = $1
RETURNING unique_id, uuid, start_mood_rating, start_mood, finish_mood_rating, finish_mood, session_completed, started_at, ends_at, deleted_at
`

type UpdateTummoBreathingMrStartingMoodByUuidParams struct {
	Uuid            uuid.UUID `json:"uuid"`
	StartMoodRating int16     `json:"start_mood_rating"`
	StartMood       string    `json:"start_mood"`
}

func (q *Queries) UpdateTummoBreathingMrStartingMoodByUuid(ctx context.Context, arg UpdateTummoBreathingMrStartingMoodByUuidParams) error {
	_, err := q.db.ExecContext(ctx, updateTummoBreathingMrStartingMoodByUuid, arg.Uuid, arg.StartMoodRating, arg.StartMood)
	return err
}
