// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: userProfileMr.sql

package db

import (
	"context"
)

const createUserProfileMr = `-- name: CreateUserProfileMr :exec
INSERT INTO users_profile_mr (
  user_id
) VALUES (
  $1
)
RETURNING user_id, total_time_spent_in_mins, deleted_at
`

func (q *Queries) CreateUserProfileMr(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, createUserProfileMr, userID)
	return err
}

const getUserProfileMrByUserId = `-- name: GetUserProfileMrByUserId :one
SELECT user_id, total_time_spent_in_mins, deleted_at FROM users_profile_mr
WHERE user_id = $1
`

func (q *Queries) GetUserProfileMrByUserId(ctx context.Context, userID int64) (UsersProfileMr, error) {
	row := q.db.QueryRowContext(ctx, getUserProfileMrByUserId, userID)
	var i UsersProfileMr
	err := row.Scan(&i.UserID, &i.TotalTimeSpentInMins, &i.DeletedAt)
	return i, err
}

const getUserProfileMrTime = `-- name: GetUserProfileMrTime :one
SELECT total_time_spent_in_mins FROM users_profile_mr
WHERE user_id = $1
`

func (q *Queries) GetUserProfileMrTime(ctx context.Context, userID int64) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserProfileMrTime, userID)
	var total_time_spent_in_mins int32
	err := row.Scan(&total_time_spent_in_mins)
	return total_time_spent_in_mins, err
}
