// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: userProfileMobile.sql

package db

import (
	"context"
)

const createUserProfileMobile = `-- name: CreateUserProfileMobile :exec
INSERT INTO users_profile_mobile (
  user_id
) VALUES (
  $1
)
RETURNING user_id, total_time_spent_in_mins, deleted_at
`

func (q *Queries) CreateUserProfileMobile(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, createUserProfileMobile, userID)
	return err
}

const getUserProfileMobileByUserId = `-- name: GetUserProfileMobileByUserId :one
SELECT user_id, total_time_spent_in_mins, deleted_at FROM users_profile_mobile
WHERE user_id = $1
`

func (q *Queries) GetUserProfileMobileByUserId(ctx context.Context, userID int64) (UsersProfileMobile, error) {
	row := q.db.QueryRowContext(ctx, getUserProfileMobileByUserId, userID)
	var i UsersProfileMobile
	err := row.Scan(&i.UserID, &i.TotalTimeSpentInMins, &i.DeletedAt)
	return i, err
}

const getUserProfileMobileTime = `-- name: GetUserProfileMobileTime :one
SELECT total_time_spent_in_mins FROM users_profile_mobile
WHERE user_id = $1
`

func (q *Queries) GetUserProfileMobileTime(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserProfileMobileTime, userID)
	var total_time_spent_in_mins int64
	err := row.Scan(&total_time_spent_in_mins)
	return total_time_spent_in_mins, err
}

const updateUserProfileMobilerTime = `-- name: UpdateUserProfileMobilerTime :exec
UPDATE users_profile_mobile
SET total_time_spent_in_mins = $1
WHERE user_id = $2
`

type UpdateUserProfileMobilerTimeParams struct {
	TotalTimeSpentInMins int64 `json:"total_time_spent_in_mins"`
	UserID               int64 `json:"user_id"`
}

func (q *Queries) UpdateUserProfileMobilerTime(ctx context.Context, arg UpdateUserProfileMobilerTimeParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfileMobilerTime, arg.TotalTimeSpentInMins, arg.UserID)
	return err
}
