// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lotusMind/meditation/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	db "github.com/lotusMind/meditation/db/sqlc"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateChakraTestOptionAnswersBatch mocks base method.
func (m *MockStore) CreateChakraTestOptionAnswersBatch(arg0 context.Context, arg1 db.CreateChakraTestOptionAnswersBatchParams) ([]db.ChakraTestOptionAnswer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChakraTestOptionAnswersBatch", arg0, arg1)
	ret0, _ := ret[0].([]db.ChakraTestOptionAnswer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChakraTestOptionAnswersBatch indicates an expected call of CreateChakraTestOptionAnswersBatch.
func (mr *MockStoreMockRecorder) CreateChakraTestOptionAnswersBatch(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChakraTestOptionAnswersBatch", reflect.TypeOf((*MockStore)(nil).CreateChakraTestOptionAnswersBatch), arg0, arg1)
}

// CreateSessionLog mocks base method.
func (m *MockStore) CreateSessionLog(arg0 context.Context, arg1 db.CreateSessionLogParams) (db.SessionLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSessionLog", arg0, arg1)
	ret0, _ := ret[0].(db.SessionLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSessionLog indicates an expected call of CreateSessionLog.
func (mr *MockStoreMockRecorder) CreateSessionLog(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSessionLog", reflect.TypeOf((*MockStore)(nil).CreateSessionLog), arg0, arg1)
}

// CreateSessionLogTransaction mocks base method.
func (m *MockStore) CreateSessionLogTransaction(arg0 context.Context, arg1 db.CreateSessionLogParams) (db.CreateSessionLogTransactionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSessionLogTransaction", arg0, arg1)
	ret0, _ := ret[0].(db.CreateSessionLogTransactionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSessionLogTransaction indicates an expected call of CreateSessionLogTransaction.
func (mr *MockStoreMockRecorder) CreateSessionLogTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSessionLogTransaction", reflect.TypeOf((*MockStore)(nil).CreateSessionLogTransaction), arg0, arg1)
}

// CreateTibetanSingingBowlMr mocks base method.
func (m *MockStore) CreateTibetanSingingBowlMr(arg0 context.Context, arg1 db.CreateTibetanSingingBowlMrParams) (db.TibetanSingingBowlMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTibetanSingingBowlMr", arg0, arg1)
	ret0, _ := ret[0].(db.TibetanSingingBowlMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTibetanSingingBowlMr indicates an expected call of CreateTibetanSingingBowlMr.
func (mr *MockStoreMockRecorder) CreateTibetanSingingBowlMr(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTibetanSingingBowlMr", reflect.TypeOf((*MockStore)(nil).CreateTibetanSingingBowlMr), arg0, arg1)
}

// CreateTummoBreathingMr mocks base method.
func (m *MockStore) CreateTummoBreathingMr(arg0 context.Context, arg1 db.CreateTummoBreathingMrParams) (db.TummoBreathingMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTummoBreathingMr", arg0, arg1)
	ret0, _ := ret[0].(db.TummoBreathingMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTummoBreathingMr indicates an expected call of CreateTummoBreathingMr.
func (mr *MockStoreMockRecorder) CreateTummoBreathingMr(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTummoBreathingMr", reflect.TypeOf((*MockStore)(nil).CreateTummoBreathingMr), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(arg0 context.Context, arg1 db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), arg0, arg1)
}

// CreateUserEmail mocks base method.
func (m *MockStore) CreateUserEmail(arg0 context.Context, arg1 db.CreateUserEmailParams) (db.CreateUserEmailRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserEmail", arg0, arg1)
	ret0, _ := ret[0].(db.CreateUserEmailRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserEmail indicates an expected call of CreateUserEmail.
func (mr *MockStoreMockRecorder) CreateUserEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserEmail", reflect.TypeOf((*MockStore)(nil).CreateUserEmail), arg0, arg1)
}

// CreateUserEmailTransaction mocks base method.
func (m *MockStore) CreateUserEmailTransaction(arg0 context.Context, arg1 db.CreateUserEmailTransactiontArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserEmailTransaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserEmailTransaction indicates an expected call of CreateUserEmailTransaction.
func (mr *MockStoreMockRecorder) CreateUserEmailTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserEmailTransaction", reflect.TypeOf((*MockStore)(nil).CreateUserEmailTransaction), arg0, arg1)
}

// CreateUserForTestingDeletion mocks base method.
func (m *MockStore) CreateUserForTestingDeletion(arg0 context.Context) (db.CreateUserForTestingDeletionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserForTestingDeletion", arg0)
	ret0, _ := ret[0].(db.CreateUserForTestingDeletionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserForTestingDeletion indicates an expected call of CreateUserForTestingDeletion.
func (mr *MockStoreMockRecorder) CreateUserForTestingDeletion(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserForTestingDeletion", reflect.TypeOf((*MockStore)(nil).CreateUserForTestingDeletion), arg0)
}

// CreateUserProfileMobile mocks base method.
func (m *MockStore) CreateUserProfileMobile(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserProfileMobile", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserProfileMobile indicates an expected call of CreateUserProfileMobile.
func (mr *MockStoreMockRecorder) CreateUserProfileMobile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserProfileMobile", reflect.TypeOf((*MockStore)(nil).CreateUserProfileMobile), arg0, arg1)
}

// CreateUserProfileMr mocks base method.
func (m *MockStore) CreateUserProfileMr(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserProfileMr", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserProfileMr indicates an expected call of CreateUserProfileMr.
func (mr *MockStoreMockRecorder) CreateUserProfileMr(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserProfileMr", reflect.TypeOf((*MockStore)(nil).CreateUserProfileMr), arg0, arg1)
}

// CreateUserTransaction mocks base method.
func (m *MockStore) CreateUserTransaction(arg0 context.Context, arg1 db.CreateUserTransactiontArgs) (db.CreateUserResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserTransaction", arg0, arg1)
	ret0, _ := ret[0].(db.CreateUserResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserTransaction indicates an expected call of CreateUserTransaction.
func (mr *MockStoreMockRecorder) CreateUserTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserTransaction", reflect.TypeOf((*MockStore)(nil).CreateUserTransaction), arg0, arg1)
}

// DeleteSessionLog mocks base method.
func (m *MockStore) DeleteSessionLog(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSessionLog", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSessionLog indicates an expected call of DeleteSessionLog.
func (mr *MockStoreMockRecorder) DeleteSessionLog(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSessionLog", reflect.TypeOf((*MockStore)(nil).DeleteSessionLog), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockStore) DeleteUser(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockStoreMockRecorder) DeleteUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockStore)(nil).DeleteUser), arg0, arg1)
}

// GetByEmail mocks base method.
func (m *MockStore) GetByEmail(arg0 context.Context, arg1 string) (db.GetByEmailRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", arg0, arg1)
	ret0, _ := ret[0].(db.GetByEmailRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockStoreMockRecorder) GetByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockStore)(nil).GetByEmail), arg0, arg1)
}

// GetChakraBracelet mocks base method.
func (m *MockStore) GetChakraBracelet(arg0 context.Context, arg1 []string) ([]db.GetChakraBraceletRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChakraBracelet", arg0, arg1)
	ret0, _ := ret[0].([]db.GetChakraBraceletRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChakraBracelet indicates an expected call of GetChakraBracelet.
func (mr *MockStoreMockRecorder) GetChakraBracelet(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChakraBracelet", reflect.TypeOf((*MockStore)(nil).GetChakraBracelet), arg0, arg1)
}

// GetChakraTestResults mocks base method.
func (m *MockStore) GetChakraTestResults(arg0 context.Context, arg1 string) ([]db.GetChakraTestResultsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChakraTestResults", arg0, arg1)
	ret0, _ := ret[0].([]db.GetChakraTestResultsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChakraTestResults indicates an expected call of GetChakraTestResults.
func (mr *MockStoreMockRecorder) GetChakraTestResults(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChakraTestResults", reflect.TypeOf((*MockStore)(nil).GetChakraTestResults), arg0, arg1)
}

// GetEmailRegistrationByTestNum mocks base method.
func (m *MockStore) GetEmailRegistrationByTestNum(arg0 context.Context, arg1 db.GetEmailRegistrationByTestNumParams) (db.GetEmailRegistrationByTestNumRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailRegistrationByTestNum", arg0, arg1)
	ret0, _ := ret[0].(db.GetEmailRegistrationByTestNumRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailRegistrationByTestNum indicates an expected call of GetEmailRegistrationByTestNum.
func (mr *MockStoreMockRecorder) GetEmailRegistrationByTestNum(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailRegistrationByTestNum", reflect.TypeOf((*MockStore)(nil).GetEmailRegistrationByTestNum), arg0, arg1)
}

// GetLatestEmailRegistration mocks base method.
func (m *MockStore) GetLatestEmailRegistration(arg0 context.Context, arg1 string) (db.GetLatestEmailRegistrationRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestEmailRegistration", arg0, arg1)
	ret0, _ := ret[0].(db.GetLatestEmailRegistrationRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestEmailRegistration indicates an expected call of GetLatestEmailRegistration.
func (mr *MockStoreMockRecorder) GetLatestEmailRegistration(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestEmailRegistration", reflect.TypeOf((*MockStore)(nil).GetLatestEmailRegistration), arg0, arg1)
}

// GetReportByCode mocks base method.
func (m *MockStore) GetReportByCode(arg0 context.Context, arg1 string) (db.GetReportByCodeRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReportByCode", arg0, arg1)
	ret0, _ := ret[0].(db.GetReportByCodeRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReportByCode indicates an expected call of GetReportByCode.
func (mr *MockStoreMockRecorder) GetReportByCode(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReportByCode", reflect.TypeOf((*MockStore)(nil).GetReportByCode), arg0, arg1)
}

// GetSessionLogByUUID mocks base method.
func (m *MockStore) GetSessionLogByUUID(arg0 context.Context, arg1 uuid.UUID) (db.SessionLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionLogByUUID", arg0, arg1)
	ret0, _ := ret[0].(db.SessionLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionLogByUUID indicates an expected call of GetSessionLogByUUID.
func (mr *MockStoreMockRecorder) GetSessionLogByUUID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionLogByUUID", reflect.TypeOf((*MockStore)(nil).GetSessionLogByUUID), arg0, arg1)
}

// GetSessionsLogByUserId mocks base method.
func (m *MockStore) GetSessionsLogByUserId(arg0 context.Context, arg1 int64) ([]db.SessionLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionsLogByUserId", arg0, arg1)
	ret0, _ := ret[0].([]db.SessionLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionsLogByUserId indicates an expected call of GetSessionsLogByUserId.
func (mr *MockStoreMockRecorder) GetSessionsLogByUserId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionsLogByUserId", reflect.TypeOf((*MockStore)(nil).GetSessionsLogByUserId), arg0, arg1)
}

// GetSessionsLogByUserIdWithOffset mocks base method.
func (m *MockStore) GetSessionsLogByUserIdWithOffset(arg0 context.Context, arg1 db.GetSessionsLogByUserIdWithOffsetParams) ([]db.SessionLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionsLogByUserIdWithOffset", arg0, arg1)
	ret0, _ := ret[0].([]db.SessionLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionsLogByUserIdWithOffset indicates an expected call of GetSessionsLogByUserIdWithOffset.
func (mr *MockStoreMockRecorder) GetSessionsLogByUserIdWithOffset(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionsLogByUserIdWithOffset", reflect.TypeOf((*MockStore)(nil).GetSessionsLogByUserIdWithOffset), arg0, arg1)
}

// GetTibetanSingingBowlMrByUniqueID mocks base method.
func (m *MockStore) GetTibetanSingingBowlMrByUniqueID(arg0 context.Context, arg1 uuid.UUID) (db.TibetanSingingBowlMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTibetanSingingBowlMrByUniqueID", arg0, arg1)
	ret0, _ := ret[0].(db.TibetanSingingBowlMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTibetanSingingBowlMrByUniqueID indicates an expected call of GetTibetanSingingBowlMrByUniqueID.
func (mr *MockStoreMockRecorder) GetTibetanSingingBowlMrByUniqueID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTibetanSingingBowlMrByUniqueID", reflect.TypeOf((*MockStore)(nil).GetTibetanSingingBowlMrByUniqueID), arg0, arg1)
}

// GetTibetanSingingBowlMrByUserID mocks base method.
func (m *MockStore) GetTibetanSingingBowlMrByUserID(arg0 context.Context, arg1 int64) ([]db.TibetanSingingBowlMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTibetanSingingBowlMrByUserID", arg0, arg1)
	ret0, _ := ret[0].([]db.TibetanSingingBowlMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTibetanSingingBowlMrByUserID indicates an expected call of GetTibetanSingingBowlMrByUserID.
func (mr *MockStoreMockRecorder) GetTibetanSingingBowlMrByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTibetanSingingBowlMrByUserID", reflect.TypeOf((*MockStore)(nil).GetTibetanSingingBowlMrByUserID), arg0, arg1)
}

// GetTibetanSingingBowlMrByUuid mocks base method.
func (m *MockStore) GetTibetanSingingBowlMrByUuid(arg0 context.Context, arg1 uuid.UUID) (db.TibetanSingingBowlMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTibetanSingingBowlMrByUuid", arg0, arg1)
	ret0, _ := ret[0].(db.TibetanSingingBowlMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTibetanSingingBowlMrByUuid indicates an expected call of GetTibetanSingingBowlMrByUuid.
func (mr *MockStoreMockRecorder) GetTibetanSingingBowlMrByUuid(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTibetanSingingBowlMrByUuid", reflect.TypeOf((*MockStore)(nil).GetTibetanSingingBowlMrByUuid), arg0, arg1)
}

// GetTummoBreathingMrByUniqueID mocks base method.
func (m *MockStore) GetTummoBreathingMrByUniqueID(arg0 context.Context, arg1 uuid.UUID) (db.TummoBreathingMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTummoBreathingMrByUniqueID", arg0, arg1)
	ret0, _ := ret[0].(db.TummoBreathingMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTummoBreathingMrByUniqueID indicates an expected call of GetTummoBreathingMrByUniqueID.
func (mr *MockStoreMockRecorder) GetTummoBreathingMrByUniqueID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTummoBreathingMrByUniqueID", reflect.TypeOf((*MockStore)(nil).GetTummoBreathingMrByUniqueID), arg0, arg1)
}

// GetTummoBreathingMrByUserID mocks base method.
func (m *MockStore) GetTummoBreathingMrByUserID(arg0 context.Context, arg1 int64) ([]db.TummoBreathingMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTummoBreathingMrByUserID", arg0, arg1)
	ret0, _ := ret[0].([]db.TummoBreathingMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTummoBreathingMrByUserID indicates an expected call of GetTummoBreathingMrByUserID.
func (mr *MockStoreMockRecorder) GetTummoBreathingMrByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTummoBreathingMrByUserID", reflect.TypeOf((*MockStore)(nil).GetTummoBreathingMrByUserID), arg0, arg1)
}

// GetTummoBreathingMrByUuid mocks base method.
func (m *MockStore) GetTummoBreathingMrByUuid(arg0 context.Context, arg1 uuid.UUID) (db.TummoBreathingMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTummoBreathingMrByUuid", arg0, arg1)
	ret0, _ := ret[0].(db.TummoBreathingMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTummoBreathingMrByUuid indicates an expected call of GetTummoBreathingMrByUuid.
func (mr *MockStoreMockRecorder) GetTummoBreathingMrByUuid(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTummoBreathingMrByUuid", reflect.TypeOf((*MockStore)(nil).GetTummoBreathingMrByUuid), arg0, arg1)
}

// GetUserByEmail mocks base method.
func (m *MockStore) GetUserByEmail(arg0 context.Context, arg1 string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockStoreMockRecorder) GetUserByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockStore)(nil).GetUserByEmail), arg0, arg1)
}

// GetUserById mocks base method.
func (m *MockStore) GetUserById(arg0 context.Context, arg1 int64) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockStoreMockRecorder) GetUserById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockStore)(nil).GetUserById), arg0, arg1)
}

// GetUserIdFromSessionLogUuid mocks base method.
func (m *MockStore) GetUserIdFromSessionLogUuid(arg0 context.Context, arg1 uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIdFromSessionLogUuid", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIdFromSessionLogUuid indicates an expected call of GetUserIdFromSessionLogUuid.
func (mr *MockStoreMockRecorder) GetUserIdFromSessionLogUuid(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIdFromSessionLogUuid", reflect.TypeOf((*MockStore)(nil).GetUserIdFromSessionLogUuid), arg0, arg1)
}

// GetUserProfileMobileByUserId mocks base method.
func (m *MockStore) GetUserProfileMobileByUserId(arg0 context.Context, arg1 int64) (db.UsersProfileMobile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfileMobileByUserId", arg0, arg1)
	ret0, _ := ret[0].(db.UsersProfileMobile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfileMobileByUserId indicates an expected call of GetUserProfileMobileByUserId.
func (mr *MockStoreMockRecorder) GetUserProfileMobileByUserId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfileMobileByUserId", reflect.TypeOf((*MockStore)(nil).GetUserProfileMobileByUserId), arg0, arg1)
}

// GetUserProfileMobileTime mocks base method.
func (m *MockStore) GetUserProfileMobileTime(arg0 context.Context, arg1 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfileMobileTime", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfileMobileTime indicates an expected call of GetUserProfileMobileTime.
func (mr *MockStoreMockRecorder) GetUserProfileMobileTime(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfileMobileTime", reflect.TypeOf((*MockStore)(nil).GetUserProfileMobileTime), arg0, arg1)
}

// GetUserProfileMrByUserId mocks base method.
func (m *MockStore) GetUserProfileMrByUserId(arg0 context.Context, arg1 int64) (db.UsersProfileMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfileMrByUserId", arg0, arg1)
	ret0, _ := ret[0].(db.UsersProfileMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfileMrByUserId indicates an expected call of GetUserProfileMrByUserId.
func (mr *MockStoreMockRecorder) GetUserProfileMrByUserId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfileMrByUserId", reflect.TypeOf((*MockStore)(nil).GetUserProfileMrByUserId), arg0, arg1)
}

// GetUserProfileMrTime mocks base method.
func (m *MockStore) GetUserProfileMrTime(arg0 context.Context, arg1 int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfileMrTime", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfileMrTime indicates an expected call of GetUserProfileMrTime.
func (mr *MockStoreMockRecorder) GetUserProfileMrTime(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfileMrTime", reflect.TypeOf((*MockStore)(nil).GetUserProfileMrTime), arg0, arg1)
}

// GetUsersByCountry mocks base method.
func (m *MockStore) GetUsersByCountry(arg0 context.Context, arg1 string) ([]db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByCountry", arg0, arg1)
	ret0, _ := ret[0].([]db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByCountry indicates an expected call of GetUsersByCountry.
func (mr *MockStoreMockRecorder) GetUsersByCountry(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByCountry", reflect.TypeOf((*MockStore)(nil).GetUsersByCountry), arg0, arg1)
}

// SoftDeleteTibetanSingingBowlMrByUniqueID mocks base method.
func (m *MockStore) SoftDeleteTibetanSingingBowlMrByUniqueID(arg0 context.Context, arg1 uuid.UUID) (db.TibetanSingingBowlMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteTibetanSingingBowlMrByUniqueID", arg0, arg1)
	ret0, _ := ret[0].(db.TibetanSingingBowlMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDeleteTibetanSingingBowlMrByUniqueID indicates an expected call of SoftDeleteTibetanSingingBowlMrByUniqueID.
func (mr *MockStoreMockRecorder) SoftDeleteTibetanSingingBowlMrByUniqueID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteTibetanSingingBowlMrByUniqueID", reflect.TypeOf((*MockStore)(nil).SoftDeleteTibetanSingingBowlMrByUniqueID), arg0, arg1)
}

// SoftDeleteTummoBreathingMrByUniqueID mocks base method.
func (m *MockStore) SoftDeleteTummoBreathingMrByUniqueID(arg0 context.Context, arg1 uuid.UUID) (db.TummoBreathingMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteTummoBreathingMrByUniqueID", arg0, arg1)
	ret0, _ := ret[0].(db.TummoBreathingMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDeleteTummoBreathingMrByUniqueID indicates an expected call of SoftDeleteTummoBreathingMrByUniqueID.
func (mr *MockStoreMockRecorder) SoftDeleteTummoBreathingMrByUniqueID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteTummoBreathingMrByUniqueID", reflect.TypeOf((*MockStore)(nil).SoftDeleteTummoBreathingMrByUniqueID), arg0, arg1)
}

// UpdateSessionFinishTransaction mocks base method.
func (m *MockStore) UpdateSessionFinishTransaction(arg0 context.Context, arg1 db.UpdateSessionFinishTransactionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionFinishTransaction", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionFinishTransaction indicates an expected call of UpdateSessionFinishTransaction.
func (mr *MockStoreMockRecorder) UpdateSessionFinishTransaction(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionFinishTransaction", reflect.TypeOf((*MockStore)(nil).UpdateSessionFinishTransaction), arg0, arg1)
}

// UpdateTibetanSingingBowlMrByUniqueID mocks base method.
func (m *MockStore) UpdateTibetanSingingBowlMrByUniqueID(arg0 context.Context, arg1 db.UpdateTibetanSingingBowlMrByUniqueIDParams) (db.TibetanSingingBowlMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTibetanSingingBowlMrByUniqueID", arg0, arg1)
	ret0, _ := ret[0].(db.TibetanSingingBowlMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTibetanSingingBowlMrByUniqueID indicates an expected call of UpdateTibetanSingingBowlMrByUniqueID.
func (mr *MockStoreMockRecorder) UpdateTibetanSingingBowlMrByUniqueID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTibetanSingingBowlMrByUniqueID", reflect.TypeOf((*MockStore)(nil).UpdateTibetanSingingBowlMrByUniqueID), arg0, arg1)
}

// UpdateTibetanSingingBowlMrByUuid mocks base method.
func (m *MockStore) UpdateTibetanSingingBowlMrByUuid(arg0 context.Context, arg1 db.UpdateTibetanSingingBowlMrByUuidParams) (db.TibetanSingingBowlMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTibetanSingingBowlMrByUuid", arg0, arg1)
	ret0, _ := ret[0].(db.TibetanSingingBowlMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTibetanSingingBowlMrByUuid indicates an expected call of UpdateTibetanSingingBowlMrByUuid.
func (mr *MockStoreMockRecorder) UpdateTibetanSingingBowlMrByUuid(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTibetanSingingBowlMrByUuid", reflect.TypeOf((*MockStore)(nil).UpdateTibetanSingingBowlMrByUuid), arg0, arg1)
}

// UpdateTibetanSingingBowlMrFinishingMoodByUuid mocks base method.
func (m *MockStore) UpdateTibetanSingingBowlMrFinishingMoodByUuid(arg0 context.Context, arg1 db.UpdateTibetanSingingBowlMrFinishingMoodByUuidParams) (db.TibetanSingingBowlMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTibetanSingingBowlMrFinishingMoodByUuid", arg0, arg1)
	ret0, _ := ret[0].(db.TibetanSingingBowlMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTibetanSingingBowlMrFinishingMoodByUuid indicates an expected call of UpdateTibetanSingingBowlMrFinishingMoodByUuid.
func (mr *MockStoreMockRecorder) UpdateTibetanSingingBowlMrFinishingMoodByUuid(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTibetanSingingBowlMrFinishingMoodByUuid", reflect.TypeOf((*MockStore)(nil).UpdateTibetanSingingBowlMrFinishingMoodByUuid), arg0, arg1)
}

// UpdateTibetanSingingBowlMrQuitByUuid mocks base method.
func (m *MockStore) UpdateTibetanSingingBowlMrQuitByUuid(arg0 context.Context, arg1 db.UpdateTibetanSingingBowlMrQuitByUuidParams) (db.TibetanSingingBowlMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTibetanSingingBowlMrQuitByUuid", arg0, arg1)
	ret0, _ := ret[0].(db.TibetanSingingBowlMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTibetanSingingBowlMrQuitByUuid indicates an expected call of UpdateTibetanSingingBowlMrQuitByUuid.
func (mr *MockStoreMockRecorder) UpdateTibetanSingingBowlMrQuitByUuid(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTibetanSingingBowlMrQuitByUuid", reflect.TypeOf((*MockStore)(nil).UpdateTibetanSingingBowlMrQuitByUuid), arg0, arg1)
}

// UpdateTibetanSingingBowlMrStartingMoodByUuid mocks base method.
func (m *MockStore) UpdateTibetanSingingBowlMrStartingMoodByUuid(arg0 context.Context, arg1 db.UpdateTibetanSingingBowlMrStartingMoodByUuidParams) (db.TibetanSingingBowlMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTibetanSingingBowlMrStartingMoodByUuid", arg0, arg1)
	ret0, _ := ret[0].(db.TibetanSingingBowlMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTibetanSingingBowlMrStartingMoodByUuid indicates an expected call of UpdateTibetanSingingBowlMrStartingMoodByUuid.
func (mr *MockStoreMockRecorder) UpdateTibetanSingingBowlMrStartingMoodByUuid(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTibetanSingingBowlMrStartingMoodByUuid", reflect.TypeOf((*MockStore)(nil).UpdateTibetanSingingBowlMrStartingMoodByUuid), arg0, arg1)
}

// UpdateTummoBreathingMrByUniqueID mocks base method.
func (m *MockStore) UpdateTummoBreathingMrByUniqueID(arg0 context.Context, arg1 db.UpdateTummoBreathingMrByUniqueIDParams) (db.TummoBreathingMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTummoBreathingMrByUniqueID", arg0, arg1)
	ret0, _ := ret[0].(db.TummoBreathingMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTummoBreathingMrByUniqueID indicates an expected call of UpdateTummoBreathingMrByUniqueID.
func (mr *MockStoreMockRecorder) UpdateTummoBreathingMrByUniqueID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTummoBreathingMrByUniqueID", reflect.TypeOf((*MockStore)(nil).UpdateTummoBreathingMrByUniqueID), arg0, arg1)
}

// UpdateTummoBreathingMrByUuid mocks base method.
func (m *MockStore) UpdateTummoBreathingMrByUuid(arg0 context.Context, arg1 db.UpdateTummoBreathingMrByUuidParams) (db.TummoBreathingMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTummoBreathingMrByUuid", arg0, arg1)
	ret0, _ := ret[0].(db.TummoBreathingMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTummoBreathingMrByUuid indicates an expected call of UpdateTummoBreathingMrByUuid.
func (mr *MockStoreMockRecorder) UpdateTummoBreathingMrByUuid(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTummoBreathingMrByUuid", reflect.TypeOf((*MockStore)(nil).UpdateTummoBreathingMrByUuid), arg0, arg1)
}

// UpdateTummoBreathingMrFinishingMoodByUuid mocks base method.
func (m *MockStore) UpdateTummoBreathingMrFinishingMoodByUuid(arg0 context.Context, arg1 db.UpdateTummoBreathingMrFinishingMoodByUuidParams) (db.TummoBreathingMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTummoBreathingMrFinishingMoodByUuid", arg0, arg1)
	ret0, _ := ret[0].(db.TummoBreathingMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTummoBreathingMrFinishingMoodByUuid indicates an expected call of UpdateTummoBreathingMrFinishingMoodByUuid.
func (mr *MockStoreMockRecorder) UpdateTummoBreathingMrFinishingMoodByUuid(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTummoBreathingMrFinishingMoodByUuid", reflect.TypeOf((*MockStore)(nil).UpdateTummoBreathingMrFinishingMoodByUuid), arg0, arg1)
}

// UpdateTummoBreathingMrQuitByUuid mocks base method.
func (m *MockStore) UpdateTummoBreathingMrQuitByUuid(arg0 context.Context, arg1 db.UpdateTummoBreathingMrQuitByUuidParams) (db.TummoBreathingMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTummoBreathingMrQuitByUuid", arg0, arg1)
	ret0, _ := ret[0].(db.TummoBreathingMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTummoBreathingMrQuitByUuid indicates an expected call of UpdateTummoBreathingMrQuitByUuid.
func (mr *MockStoreMockRecorder) UpdateTummoBreathingMrQuitByUuid(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTummoBreathingMrQuitByUuid", reflect.TypeOf((*MockStore)(nil).UpdateTummoBreathingMrQuitByUuid), arg0, arg1)
}

// UpdateTummoBreathingMrStartingMoodByUuid mocks base method.
func (m *MockStore) UpdateTummoBreathingMrStartingMoodByUuid(arg0 context.Context, arg1 db.UpdateTummoBreathingMrStartingMoodByUuidParams) (db.TummoBreathingMr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTummoBreathingMrStartingMoodByUuid", arg0, arg1)
	ret0, _ := ret[0].(db.TummoBreathingMr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTummoBreathingMrStartingMoodByUuid indicates an expected call of UpdateTummoBreathingMrStartingMoodByUuid.
func (mr *MockStoreMockRecorder) UpdateTummoBreathingMrStartingMoodByUuid(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTummoBreathingMrStartingMoodByUuid", reflect.TypeOf((*MockStore)(nil).UpdateTummoBreathingMrStartingMoodByUuid), arg0, arg1)
}

// UpdateUser mocks base method.
func (m *MockStore) UpdateUser(arg0 context.Context, arg1 db.UpdateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockStoreMockRecorder) UpdateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockStore)(nil).UpdateUser), arg0, arg1)
}

// UpdateUserProfileMobilerTime mocks base method.
func (m *MockStore) UpdateUserProfileMobilerTime(arg0 context.Context, arg1 db.UpdateUserProfileMobilerTimeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProfileMobilerTime", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserProfileMobilerTime indicates an expected call of UpdateUserProfileMobilerTime.
func (mr *MockStoreMockRecorder) UpdateUserProfileMobilerTime(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProfileMobilerTime", reflect.TypeOf((*MockStore)(nil).UpdateUserProfileMobilerTime), arg0, arg1)
}

// UpdateUserProfileMrTime mocks base method.
func (m *MockStore) UpdateUserProfileMrTime(arg0 context.Context, arg1 db.UpdateUserProfileMrTimeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProfileMrTime", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserProfileMrTime indicates an expected call of UpdateUserProfileMrTime.
func (mr *MockStoreMockRecorder) UpdateUserProfileMrTime(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProfileMrTime", reflect.TypeOf((*MockStore)(nil).UpdateUserProfileMrTime), arg0, arg1)
}
